// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA58gy3EbTcCVnKDa7uHyt4VEruzkoou9s',
    appId: '1:635532014562:web:2f7e78e2f1c2fa1d457fbb',
    messagingSenderId: '635532014562',
    projectId: 'chat-app-flutter-8633d',
    authDomain: 'chat-app-flutter-8633d.firebaseapp.com',
    storageBucket: 'chat-app-flutter-8633d.firebasestorage.app',
    measurementId: 'G-WVQPHWGEG4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEYEFuQTk-FUC2cr1pO3WFRy_QcUH-o7I',
    appId: '1:635532014562:android:c28e17ea10b4b733457fbb',
    messagingSenderId: '635532014562',
    projectId: 'chat-app-flutter-8633d',
    storageBucket: 'chat-app-flutter-8633d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOYLzSg6CxvMhUbhxLIsUDx53dP9GJLZw',
    appId: '1:635532014562:ios:5ca9ff01ded35982457fbb',
    messagingSenderId: '635532014562',
    projectId: 'chat-app-flutter-8633d',
    storageBucket: 'chat-app-flutter-8633d.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOYLzSg6CxvMhUbhxLIsUDx53dP9GJLZw',
    appId: '1:635532014562:ios:5ca9ff01ded35982457fbb',
    messagingSenderId: '635532014562',
    projectId: 'chat-app-flutter-8633d',
    storageBucket: 'chat-app-flutter-8633d.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA58gy3EbTcCVnKDa7uHyt4VEruzkoou9s',
    appId: '1:635532014562:web:6479f2dcc7181e18457fbb',
    messagingSenderId: '635532014562',
    projectId: 'chat-app-flutter-8633d',
    authDomain: 'chat-app-flutter-8633d.firebaseapp.com',
    storageBucket: 'chat-app-flutter-8633d.firebasestorage.app',
    measurementId: 'G-LZ739QJ7BW',
  );
}
